### ISSUE TITLE
Change/Set/Define Rancher URL

### ISSUE THREAD

**Issue by Hunter21007** [entrecode/rancher-updater#1]
Hello,

I would try your tool, but i have a question how i can define the Rancher url?
I have seen it is defined as a constant and i have no clue how to set it from commandline.

Thanks

**Comment by simon-scherzinger** [comment]
Thanks for reporting!

I just released version 0.3.2 which should fix your issue. Now you can use the commandline argument `--url` or environment variable `RANCHER_URL` to specify your rancher server url.

**Comment by Hunter21007** [comment]
Thanks a lot, i will try
