### ISSUE TITLE
Possibility of "in-place-update"

### ISSUE THREAD

**Issue by Hunter21007** [entrecode/rancher-updater#3]
Hi i have used your tool and it is great!

the only thing which is needed to meant in the readmy is that rancher-compose requires environment key and can not work with account keys (https://github.com/rancher/rancher/issues/6965)

Bu i have another question: i need a possibility to perform "in-place upgrade" without changing service identity (without need to delete it), because i am using links outside of the stack and they get broken.

It would be nice is there would be a possibility to add modified upgrade process where `create-stop/delete`  is changed to `upgrade-rollback/confirm`

Thanks for evaluation in advance!

**Comment by Hunter21007** [comment]
I have modified updateStack in rancher-compose bindings and tested the process.
So if the servcie-name does not changes (which is controlled with the tpl.yml)
the rancher performs an inplace update which can be rollbacked.
calling rancher-compose up with -c argument confirms the update
so basically it could work. And would be very appreciated :)

**Comment by Hunter21007** [comment]
Oh, sorry just found the place regarding API key :)

**Comment by simon-scherzinger** [comment]
Closing this for now.

Hunter, if you find time to create a new PR feel free to open one. :-)
